const CONFIG = {
    titleWeb: "Lời tỏ tình dễ thương",
    introTitle: 'Quỳnh Gaby',
    introDesc: `Nếu anh là nhà thơ anh sẽ viết tặng em những vần thơ cháy bỏng,
    Nếu anh là nhạs sỹ anh sẽ viết tặng em những bản tình ca bất hủ,
    Nếu anh là lập trình viên anh sẽ viết nên những đoạn mã ngập tràn hương vị tình yêu,
     Và nếu anh có thể anh sẽ làm tất cả vì em.`,
    btnIntro: '^^Kính thưa bạn Quỳnh^^',
    title: 'Phải chăng anh đã yêu ngay từ cái nhìn đầu tiên 🥰',
    desc: 'Làm người yêu anh nha Quỳnh Gaby ',
    btnYes: 'Dạ anh <33',
    btnNo: 'Không nha anh :3',
    question: 'Em có điều gì muốn nói với anh không <3',
    btnReply: 'Em cũng yêu anh á <3',
    reply: 'Yêu thì yêu mà không yêu thì yêu <33333333',
    mess: 'Anh biết mà 🥰. A sẽ luôn thương em 😘😘',
    messDesc: 'Chúng ta bắt đầu hẹn hò nhé 😘😘.',
    btnAccept: 'Dạ anh <3',
    messLink: 'https://github.com/zukahai/Confess-Crush' //link mess của các bạn. VD: https://www.facebook.com/messages/t/100014188333536
}
